### PR TITLE
Autumn 2022 Update

### PR DESCRIPTION
**Pull request by chirag-ghosh**
Tasks Performed:
1. Changed npm to yarn. (Reverted)
2. Ran `chillzone` to get Autumn 2022 data. Note: First-year schedule is not present as classes have not started yet.
3. `ET60029` takes place at `V1` instead of `NR122`. Added that in `problems.json`. (Please let me know if I need to make a PR to add that in the main repo).
4. Removed unused data files from root.

### CODE REVIEW

**Comment by thealphadollar** [comment]
Hey @chirag-ghosh I would request you to self-review the PR once 😓

**Comment by chirag-ghosh** [comment]
I ran the Webapp and checked with my courses and they were correct. Please do let me know if there are any further changes that need to be made.

**Review by thealphadollar — CHANGES_REQUESTED** [review]
@chirag-ghosh Thanks for the PR. 

1. Please add back the package-lock.json file.
2. Remove the yarn.lock file.

Everything else looks good to me, I was a bit confused with the changes earlier.

Thanks for removing the files from the root directory.

**Comment by chirag-ghosh** [comment]
Apologies for the previous change. Reverted that. Please review again.

**Review by thealphadollar — APPROVED** [review]

**Pull request merged**
