### PR TITLE
Add the logo in svg and the favicon (see issue #5)

### PR DESCRIPTION
**Pull request by hugo-s29**
I added the logo to the navbar (done with PNG in issue #6 but done in SVG).
I also added the favicon in ICO and SVG format  (and modified the manifest file).

### CODE REVIEW

**Comment by hugo-s29** [comment]
The conflicts of the pull request are due to
* The favicon has been changed while I was coding. However, its size is 32x32. The one in the pull request is 256x256 so bigger.
* The App.js file has been changed because I added the logo in SVG.

**Comment by icyflame** [comment]
@hugo-s29 Please merge the latest master branch into your feature branch, fix the conflicts and re-request review from a maintainer. 👍

**Comment by hugo-s29** [comment]
Hi @icyflame, 
I've resolved all the conflicts, everything is ready to merge.
Hugo

**Review by thealphadollar — COMMENTED** [review]
LGTM. Thank you for your contribution to Metakgp.

**Review by thealphadollar — APPROVED** [review]

**Pull request merged**
