### PR TITLE
Add option to filter classrooms by classroom complex

### PR DESCRIPTION
**Pull request by parth-paradkar**
This will add an option for the user to select the classroom complex (NR, NC, Vikramshila)  

pr1

For example, on selecting NC:  

pr2

### CODE REVIEW

**Comment by thealphadollar** [comment]
Hey Parth, this looks sleek. Thanks a lot. I would request you to add it
for floor as well since that should be equally easy to implement.

I'd also request you to please add, "Choose the slot, floor and area you
want to chill at:"

**Review by thealphadollar — CHANGES_REQUESTED** [review]
Everything is great; just a minor update and a feature request as commented.

**Comment by parth-paradkar** [comment]
I had a doubt - Does selecting a floor make sense with V1, V2, V3, V4? What should the app do with regards to the floor selection when Vikramshila is selected?

**Comment by thealphadollar** [comment]
Do not consider them; show all for them regardless of floor.

**Comment by parth-paradkar** [comment]
Ok cool.

**Comment by parth-paradkar** [comment]
Changes made as requested. Working as expected.  

pr3

**Review by thealphadollar — APPROVED** [review]
LGTM. I've not tested it on my system but everything looks good to me according to the changes made.

Thank you @thescriptninja for the pull request and the new dope feature.

**Pull request merged**
